### ISSUE TITLE
Only working in DEBUG mode?

### ISSUE THREAD

**Issue by dradovic** [maximkornilov/MSBuild.CopyContentLinkedFiles#1]
Hi, thanks for providing this neat NuGet.

One thing I'm noticing is that it only works when compiling in DEBUG mode. Is this so?

**Comment by maximkornilov** [comment]
No, it should work for all modes. There is no any condition which limits it to work only for DEBUG mode.

**Comment by dradovic** [comment]
Yes. You're right. I forgot to add my file to the script bundle and in release mode it was optimized away. Your package is working as expected. Thanks again!
