### ISSUE TITLE
Manually execute copy process?

### ISSUE THREAD

**Issue by gilm0079** [maximkornilov/MSBuild.CopyContentLinkedFiles#4]
Hi,

We have a solution with a few websites in it that.  Those websites use some of the same files so we have a common project that has the source files and VS linked files in each website.  We use web essentials for bundling those js and css files.  Web essentials requires physical files (not linked files) to process the bundling which is why we added this nuget package to make the physical files exist on the file system for web essentials to use.  Before we used linked files (in other projects) we could be debugging in VS and change js files, web essentials would re-bundle on the save and the browser would get the updated changes on a refresh. Now we have to restart VS debugging to kick off this build process so this project copies the files for web essentials to use.

Long way of getting to the question, but is there a way to manually execute this copy process without going through the build?  I don't see any hooks to the project build events and it isn't in the task runner.  This would be nice as a workaround to updating the files.  Or if it was watching for file changes and did a single file copy on each file change that would be super helpful.

**Comment by maximkornilov** [comment]
This package adds single `CopyLinkedContentFiles` target to project which can be run manually as any other MSBuild target. Target is registered to be called before `BuildDependsOn` target in project build pipeline. You can run it manually by executing MSBuild with passing target as parameter. In this case, only this target will be executed without full build.  This is an example of the command which can be used to run required target manually:
```
MSBuild.exe MyProject.proj /t:CopyLinkedContentFiles
```

To make it watching for changes, you can try to use dotnet cli watch tool (it is part of the DotNet core tooling). It is designed especially for the case you are looking for and allows to run any command base on directory/file changes. For example, you can run `CopyLinkedContentFiles` target in watch mode using the following command: 
```
dotnet watch msbuild /t:CopyLinkedContentFiles
```
This will watch for changes and call CopyLinkedContentFiles target everytime files are changed. There is an ability to specify files/directories to watch/exclude.  I suppose [this](http://www.natemcmaster.com/blog/2017/01/03/dotnet-watch-msbuild/) is a good article which shows some usage examples. Note that currently there is 2.0 version of the DotNet Core.

Hope this info can be helpful.
